### ISSUE TITLE
ManifestHandler: "Response has already been written"

### ISSUE THREAD

**Issue by ksclarke** [ksclarke/jiiify#10]
[DEBUG] i.freelibrary.jiiify.handlers.ManifestHandler | info.freelibrary.jiiify.handlers.ManifestHandler is failing this RoutingContext
[WARN] i.f.jiiify.handlers.IIIFErrorHandler | Internal Server Error
[ERROR] i.f.jiiify.handlers.IIIFErrorHandler | Internal Server Error
io.vertx.core.impl.NoStackTraceThrowable: Response status code [404] for S3 key(s): pairtree_root/ar/k~/=2/11/98/=z/18/c9/x9/s/ark~=21198=z18c9x9s/manifest.json [message: Not Found]
[ERROR] io.vertx.ext.web.impl.RoutingContextImplBase | Unexpected exception in route
java.lang.IllegalStateException: Response has already been written
    at io.vertx.core.http.impl.HttpServerResponseImpl.checkWritten(HttpServerResponseImpl.java:559)
    at io.vertx.core.http.impl.HttpServerResponseImpl.end0(HttpServerResponseImpl.java:391)
    at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:309)
    at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:294)
    at info.freelibrary.jiiify.handlers.IIIFErrorHandler.handle(IIIFErrorHandler.java:80)
    at info.freelibrary.jiiify.handlers.IIIFErrorHandler.handle(IIIFErrorHandler.java:13)
    at io.vertx.ext.web.impl.RouteImpl.handleFailure(RouteImpl.java:222)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:76)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:94)
    at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:380)
    at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:127)
    at info.freelibrary.jiiify.handlers.JiiifyHandler.fail(JiiifyHandler.java:110)
    at info.freelibrary.jiiify.handlers.JiiifyHandler.fail(JiiifyHandler.java:92)
    at info.freelibrary.jiiify.handlers.ManifestHandler.lambda$handle$19(ManifestHandler.java:83)
    at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
    at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:148)
    at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:153)
    at info.freelibrary.pairtree.s3.S3PairtreeObject.lambda$find$14(S3PairtreeObject.java:314)
    at io.vertx.core.http.impl.HttpClientRequestImpl.doHandleResponse(HttpClientRequestImpl.java:423)
    at io.vertx.core.http.impl.HttpClientRequestBase.handleResponse(HttpClientRequestBase.java:123)
    at io.vertx.core.http.impl.ClientConnection.handleResponse(ClientConnection.java:310)
    at io.vertx.core.http.impl.ClientHandler.doMessageReceived(ClientHandler.java:68)
    at io.vertx.core.http.impl.ClientHandler.doMessageReceived(ClientHandler.java:37)
    at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
    at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ksclarke** [comment]
Fixed awhile ago but neglected to close this ticket.
